name: Update Devices
on:
  schedule:
    - cron: '0 0 */14 * *' # Run every 14 days
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run devices generator
        run: node scripts/generate-devices.js
      - name: Commit and Push
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'actions@github.com'
          git add public/filters.json
          git commit -m "Update devices" || exit 0
          git push