name: Update Steam Games
on:
  schedule:
    - cron: '0 0 1 * *' # Run on 1st of every month
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run games generator
        run: node scripts/generate-games.js
      - name: Commit and Push
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'actions@github.com'
          git add public/filters.json
          git commit -m "Update Steam games" || exit 0
          git push