name: Update GPUs
on:
  schedule:
    - cron: '0 0 */14 * *' # Run every 14 days
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install @supabase/supabase-js
      - name: Run GPUs generator
        run: node scripts/generate-gpus.js
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      - name: Commit and Push
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'actions@github.com'
          git add public/filters.json
          git commit -m "Update GPUs" || exit 0
          git push